name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: check if file exits
        run: |
          test -f ./test.txt
          test -f ./test.txts
          test -f ./test.txts


        


